version: '3.6'
services:
  db:
    environment:
      POSTGRES_PASSWORD: postgres

  backend: &backend
    build: .
    depends_on:
      - db
      - redis
    volumes:
      - ./:/app/
      - pudb_volume:/root/.config/pudb/
    ports:
      - 127.0.0.1:5000:5000

  worker: &worker
    <<: *backend
    command: celery -A say.celery worker --autoscale=8,1 --loglevel=WARNING -B -S redbeat.RedBeatScheduler -Q celery -Ofair
    healthcheck:
      test: echo

  slow-worker:
    <<: *worker
    command: celery -A say.celery worker --autoscale=4,1 --loglevel=WARNING -S redbeat.RedBeatScheduler -Q slow -Ofair

  flower:
    <<: *worker
    command: celery -A say.celery flower
    environment:
      - FLOWER_PERSISTENT=true
      - FLOWER_DB=/flower/db
    volumes:
      - flower_volume:/flower

volumes:
  pudb_volume: