version: '3.6'

services:
  redis:
    image: redis:6
    volumes:
      - redis_volume:/data
  db:
    image: postgres:12
    environment:
      POSTGRES_DB:       ${SAY_POSTGRES_DB}
      POSTGRES_USER:     ${SAY_POSTGRES_USER}
      POSTGRES_PASSWORD: ${SAY_POSTGRES_PASSWORD}
    volumes:
      - postgres_volume:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    volumes:
      - rabbitmq_data_volume:/var/lib/rabbitmq/
      - rabbitmq_log_volume:/var/log/rabbitmq/
    environment:
      RABBITMQ_DEFAULT_USER:  $SAY_RABBITMQ_DEFAULT_USER
      RABBITMQ_DEFAULT_PASS:  $SAY_RABBITMQ_DEFAULT_PASS
      RABBITMQ_DEFAULT_VHOST: $SAY_RABBITMQ_VHOST
  backend: &backend
    image: $CONTAINER_IMAGE
    env_file:
      - .env
    configs:
      - source: ${STACK}-${TIMESTAMP}.env
        target: .env
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
    networks:
      - traefik-public
      - default
    expose:
      - 5000
    volumes:
      - ./config.json:/app/config.json
      - ./apimd-config.cfg:/app/apimd-config-prod.cfg
      - backend_volume:/app/data
    depends_on:
      - "redis"
      - "db"
      - "rabbitmq"
  worker:
    <<: *backend
    command: celery -A say.api.app.celery worker --concurrency 2 --loglevel=WARNING -B -S redbeat.RedBeatScheduler
volumes:
  redis_volume:
  postgres_volume:
  rabbitmq_data_volume:
  rabbitmq_log_volume:
  backend_volume:
networks:
  traefik-public:
    external: true
configs:
  backned-configs:
    name: ${STACK}-${TIMESTAMP}.env
    external: true
