version: '3.6'

services:
  redis:
    image: redis:6
    volumes:
      - redis_volume:/data

  db:
    image: postgres:12
    environment:
      POSTGRES_DB: say
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  backend: &backend
    depends_on:
      - db
      - redis
    environment:
      SAY_ENVIRONMENT: ${ENVIRONMENT:-dev}
    networks:
      - traefik-public
      - default
    expose:
      - 5000
    volumes:
      # - ./:/app/
      - media_volume/:/app/files

  worker: &worker
    <<: *backend
    command: celery -A say.celery worker --autoscale=8,1 --loglevel=WARNING -B -S redbeat.RedBeatScheduler -Q celery -Ofair
    healthcheck:
      test: echo

  slow-worker:
    <<: *worker
    command: celery -A say.celery worker --autoscale=4,1 --loglevel=WARNING -S redbeat.RedBeatScheduler -Q slow -Ofair

  flower:
    <<: *worker
    command: celery -A say.celery flower
    environment:
      - FLOWER_PERSISTENT=true
      - FLOWER_DB=/flower/db
    volumes:
      - flower_volume:/flower

  media:
    image: flashspys/nginx-static
    networks:
      - traefik-public
    volumes:
      - media_volume:/static

  static:
    image: flashspys/nginx-static
    networks:
      - traefik-public
    expose:
      - 80
    volumes:
      - static_volume:/static

volumes:
  redis_volume:
  postgres_volume:
  media_volume:
  static_volume:
  flower_volume:

networks:
  traefik-public:

configs:
  backned-config:
    name: ${STACK_NAME:-say}.env
    external: true
