version: '3.6'

services:
  redis:
    image: redis:6
    volumes:
      - redis_volume:/data
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: say
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
    secrets:
      - postgres-password
    volumes:
      - postgres_volume:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    volumes:
      - rabbitmq_data_volume:/var/lib/rabbitmq/
      - rabbitmq_log_volume:/var/log/rabbitmq/
    environment:
      RABBITMQ_DEFAULT_USER: say
      RABBITMQ_DEFAULT_PASS: /run/secrets/rabbitmq-password
      RABBITMQ_DEFAULT_VHOST: say
    secrets:
      - rabbitmq-password
  backend: &backend
    image: $CONTAINER_IMAGE
    configs:
      - source: backned-config
        target: .env
    secrets:
      - source: postgres-password
        target: postgres-password
      - source: rabbitmq-password
        target: rabbitmq-password
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
    networks:
      - traefik-public
      - default
    expose:
      - 5000
    volumes:
      - backend_volume:/app/data
    depends_on:
      - redis
      - db
      - rabbitmq
    deploy:
      placement:
        constraints:
          - node.labels.${ENVIRONMENT} == true
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.${STACK_NAME}-backend-http.entrypoints=http
        - traefik.http.routers.${STACK_NAME}-backend-http.rule=Host(`${DOMAIN?Variable not set}`) && PathPrefix(`/api`)
        - traefik.http.routers.${STACK_NAME}-backend-http.service=${STACK_NAME}-backend
        - traefik.http.routers.${STACK_NAME}-backend-http.middlewares=https-redirect
        - traefik.http.routers.${STACK_NAME}-backend.entrypoints=https
        - traefik.http.routers.${STACK_NAME}-backend.rule=Host(`${DOMAIN?Variable not set}`) && PathPrefix(`/api`)
        - traefik.http.routers.${STACK_NAME}-backend.service=${STACK_NAME}-backend
        - traefik.http.routers.${STACK_NAME}-backend.tls=true
        - traefik.http.routers.${STACK_NAME}-backend.tls.certresolver=le
        - traefik.http.services.${STACK_NAME}-backend.loadbalancer.server.port=5000
  worker:
    <<: *backend
    command: celery -A say.api.app.celery worker --concurrency 2 --loglevel=WARNING -B -S redbeat.RedBeatScheduler
volumes:
  redis_volume:
  postgres_volume:
  rabbitmq_data_volume:
  rabbitmq_log_volume:
  backend_volume:
networks:
  traefik-public:
    external: true
configs:
  backned-config:
    name: ${STACK_NAME}.env
    external: true
secrets:
  postgres-password:
    name: ${STACK_NAME}-postgres-password
    external: true
  rabbitmq-password:
    name: ${STACK_NAME}-rabbitmq-password
    external: true