version: '3.6'
services:
  db:
    ports:
      - 35432:5432

  sqlbak:
    image: pranasnet/sqlbak
    volumes:
      - sqlbak_local_data:/opt/sqlbak
      - sqlbak_backups:/tmp/sqlbak

  pgbackups:
    image: prodrigestivill/postgres-backup-local:12-alpine
    secrets:
      - postgres-password
    volumes:
      - postgres_backup_volume:/backups
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=say
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-password
      - POSTGRES_EXTRA_OPTS=-Z9 --schema=public --blobs
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=30
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=80
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.${ENVIRONMENT} == true

volumes:
  sqlbak_local_data:
  sqlbak_backups:
  postgres_backup_volume:
