FROM python:3.8

# We copy just the requirements.txt first to leverage Docker cache
COPY ./requirements.txt /app/requirements.txt
WORKDIR /app
RUN pip --cache-dir=.pip install -r requirements.txt

COPY . /app
CMD ["./scripts/run-staging.sh"]

