version: '3.6'
services:
  db:
    ports:
      - 35432:5432

  sqlbak:
    image: pranasnet/sqlbak
    volumes:
      - sqlbak_local_data:/opt/sqlbak
      - sqlbak_backups:/tmp/sqlbak

volumes:
 sqlbak_local_data:
 sqlbak_backups:
