"""empty message

Revision ID: 031739cac62c
Revises: 40570cef36d8
Create Date: 2020-02-23 20:01:47.605450

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = '031739cac62c'
down_revision = '40570cef36d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_email_verified', sa.Boolean(), server_default='FALSE', nullable=False))
    op.add_column('user', sa.Column('is_phonenumber_verified', sa.Boolean(), server_default='FALSE', nullable=False))
    op.execute('UPDATE "user" SET is_email_verified = "isVerified";')
    op.drop_column('user', 'isVerified')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('isVerified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('user', 'is_phonenumber_erified')
    op.drop_column('user', 'is_email_verified')
    # ### end Alembic commands ###
