"""empty message

Revision ID: 031d68e80bac
Revises: 8a0bca2890cc
Create Date: 2020-11-08 01:37:26.826516

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = '031d68e80bac'
down_revision = '8a0bca2890cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'receipt',
        sa.Column('created', sa.DateTime(), nullable=False),
        sa.Column('updated', sa.DateTime(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('owner_id', sa.Integer(), nullable=False),
        sa.Column('attachment', sa.Unicode(length=128), nullable=False),
        sa.Column('code', sa.Unicode(length=64), nullable=False),
        sa.Column('deleted', sa.DateTime(), nullable=True),
        sa.Column('description', sa.Unicode(length=1024), nullable=True),
        sa.Column('title', sa.Unicode(length=128), nullable=True),
        sa.Column('is_public', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ['owner_id'],
            ['social_worker.id'],
            name=op.f('receipt_owner_id_social_worker_fkey'),
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('receipt_pkey')),
        sa.UniqueConstraint('code', 'deleted', name=op.f('receipt_code_key')),
    )
    op.create_index(op.f('receipt_code_idx'), 'receipt', ['code'], unique=False)
    op.create_table(
        'need_receipt',
        sa.Column('created', sa.DateTime(), nullable=False),
        sa.Column('updated', sa.DateTime(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('need_id', sa.Integer(), nullable=False),
        sa.Column('sw_id', sa.Integer(), nullable=False),
        sa.Column('receipt_id', sa.Integer(), nullable=False),
        sa.Column('deleted', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ['need_id'], ['need.id'], name=op.f('need_receipt_need_id_need_fkey')
        ),
        sa.ForeignKeyConstraint(
            ['receipt_id'],
            ['receipt.id'],
            name=op.f('need_receipt_receipt_id_receipt_fkey'),
        ),
        sa.ForeignKeyConstraint(
            ['sw_id'],
            ['social_worker.id'],
            name=op.f('need_receipt_sw_id_social_worker_fkey'),
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('need_receipt_pkey')),
        sa.UniqueConstraint(
            'need_id', 'receipt_id', 'deleted', name=op.f('need_receipt_need_id_key')
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('need_receipt')
    op.drop_index(op.f('receipt_code_idx'), table_name='receipt')
    op.drop_table('receipt')
    # ### end Alembic commands ###
