"""empty message

Revision ID: 04432c7759dd
Revises: 395b2489c205
Create Date: 2020-07-03 16:10:38.239031

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = '04432c7759dd'
down_revision = '395b2489c205'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('need', sa.Column('dkc', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('need', 'dkc')
    # ### end Alembic commands ###
