"""empty message

Revision ID: 0b00bc8160f7
Revises: 120e79de55cd
Create Date: 2022-04-05 17:28:46.731819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b00bc8160f7'
down_revision = '120e79de55cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('emojiu', sa.Unicode(length=191), nullable=True))
    op.drop_column('countries', 'emojiU')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('emojiU', sa.VARCHAR(length=191), autoincrement=False, nullable=True))
    op.drop_column('countries', 'emojiu')
    # ### end Alembic commands ###
