"""empty message

Revision ID: 0bae2c4e2f34
Revises: d7af0041fbf7
Create Date: 2021-09-29 14:02:38.719420

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = '0bae2c4e2f34'
down_revision = 'd7af0041fbf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('receive_email', sa.Boolean(), nullable=True))
    op.execute('UPDATE "user" SET receive_email = true;')
    op.execute('ALTER TABLE "user" ALTER COLUMN receive_email SET NOT NULL;')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'receive_email')
    # ### end Alembic commands ###
