"""empty message

Revision ID: 0ebe70e88c88
Revises: 85df3eb096d5
Create Date: 2021-06-11 16:20:45.340859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ebe70e88c88'
down_revision = '85df3eb096d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_payments', sa.Column('card_no', sa.String(), nullable=True))
    op.add_column('cart_payments', sa.Column('transaction_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart_payments', 'transaction_date')
    op.drop_column('cart_payments', 'card_no')
    # ### end Alembic commands ###
