"""empty message

Revision ID: 120e79de55cd
Revises: ce20d02b6b94
Create Date: 2022-04-05 17:25:59.823181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '120e79de55cd'
down_revision = 'ce20d02b6b94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('phone_code', sa.Unicode(length=255), nullable=True))
    op.drop_column('countries', 'phonecode')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('phonecode', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('countries', 'phone_code')
    # ### end Alembic commands ###
