"""empty message

Revision ID: 1324530cace6
Revises: f56b3f2e2f9a
Create Date: 2020-08-07 22:25:28.213124

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = '1324530cace6'
down_revision = 'f56b3f2e2f9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('''
        UPDATE invitations
        SET inviter_id = (
            SELECT id from "user" WHERE "userName" = 'SAY'
        );
    ''')
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
