"""empty message

Revision ID: 13273160e75b
Revises: 1df11408a1af
Create Date: 2022-04-05 17:39:24.399186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13273160e75b'
down_revision = '1df11408a1af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('state_name', sa.Unicode(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cities', 'state_name')
    # ### end Alembic commands ###
