"""empty message

Revision ID: 133ac22dd633
Revises: d509c993c888
Create Date: 2020-01-23 21:53:37.004693

"""
import sqlalchemy as sa
import sqlalchemy_utils

from alembic import op


# revision identifiers, used by Alembic.
revision = '133ac22dd633'
down_revision = 'd509c993c888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'social_worker',
        sa.Column(
            'locale',
            sqlalchemy_utils.types.locale.LocaleType(),
            nullable=False,
            server_default='fa',
        )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('social_worker', 'locale')
    # ### end Alembic commands ###
