"""empty message

Revision ID: 19a5d398fe58
Revises: 6fe757333c0a
Create Date: 2020-04-28 21:15:55.971514

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = '19a5d398fe58'
down_revision = '6fe757333c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE "user" ALTER COLUMN postal_code TYPE VARCHAR(10);')
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
