"""empty message

Revision ID: 19bc90e76676
Revises: 1e8bd01ac5cb
Create Date: 2022-04-10 12:10:09.217049

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = '19bc90e76676'
down_revision = '1e8bd01ac5cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ngo', sa.Column('city_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f('ngo_city_id_cities_fkey'), 'ngo', 'cities', ['city_id'], ['id']
    )
    op.execute('''UPDATE ngo SET city_id = 135129;''')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ngo_city_id_cities_fkey'), 'ngo', type_='foreignkey')
    op.drop_column('ngo', 'city_id')
    # ### end Alembic commands ###
