"""empty message

Revision ID: 1a333a9886a1
Revises: 6a51baa0e0d9
Create Date: 2021-12-07 10:58:24.609429

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = '1a333a9886a1'
down_revision = '6a51baa0e0d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_unique_constraint(
        op.f('social_worker_emailAddress_key'), 'social_worker', ['emailAddress']
    )
    op.create_unique_constraint(
        op.f('social_worker_phoneNumber_key'), 'social_worker', ['phoneNumber']
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f('social_worker_phoneNumber_key'), 'social_worker', type_='unique'
    )
    op.drop_constraint(
        op.f('social_worker_emailAddress_key'), 'social_worker', type_='unique'
    )
    # ### end Alembic commands ###
