"""empty message

Revision ID: 1cb0e0e40c3c
Revises: 04d163651950
Create Date: 2020-01-22 16:49:20.358450

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1cb0e0e40c3c'
down_revision = '04d163651950'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('child', sa.Column('firstName_translations', postgresql.HSTORE(text_type=sa.Text()), nullable=True))
    op.add_column('child', sa.Column('lastName_translations', postgresql.HSTORE(text_type=sa.Text()), nullable=True))
    op.execute('''update child set "firstName_translations" = hstore('en', "firstName") || hstore('fa', '');''')
    op.execute('''update child set "lastName_translations" = hstore('en', "lastName") || hstore('fa', '');''')

    op.drop_column('child', 'firstName')
    op.drop_column('child', 'lastName')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('child', sa.Column('lastName', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('child', sa.Column('firstName', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('child', 'lastName_translations')
    op.drop_column('child', 'firstName_translations')
    # ### end Alembic commands ###
