"""empty message

Revision ID: 1df11408a1af
Revises: ff9f4e8d194d
Create Date: 2022-04-05 17:35:34.459817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1df11408a1af'
down_revision = 'ff9f4e8d194d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('states', 'latitude',
               existing_type=sa.NUMERIC(precision=10, scale=8),
               nullable=True)
    op.alter_column('states', 'longitude',
               existing_type=sa.NUMERIC(precision=11, scale=8),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('states', 'longitude',
               existing_type=sa.NUMERIC(precision=11, scale=8),
               nullable=False)
    op.alter_column('states', 'latitude',
               existing_type=sa.NUMERIC(precision=10, scale=8),
               nullable=False)
    # ### end Alembic commands ###
