"""empty message

Revision ID: 1e8bd01ac5cb
Revises: ed298c4f0cf1
Create Date: 2022-04-05 21:07:22.612647

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = '1e8bd01ac5cb'
down_revision = 'ed298c4f0cf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_worker', sa.Column('city_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f('social_worker_city_id_cities_fkey'),
        'social_worker',
        'cities',
        ['city_id'],
        ['id'],
    )
    op.add_column(
        'social_worker_version',
        sa.Column('city_id', sa.Integer(), autoincrement=False, nullable=True),
    )

    op.execute(
        '''
        UPDATE social_worker
        SET city_id = CASE
            WHEN city = 1 THEN 135129
            WHEN city = 2 THEN 134664
            ELSE null
        END;'''
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('social_worker_version', 'city_id')
    op.drop_constraint(
        op.f('social_worker_city_id_cities_fkey'), 'social_worker', type_='foreignkey'
    )
    op.drop_column('social_worker', 'city_id')
    # ### end Alembic commands ###
