"""empty message

Revision ID: 1edf57319173
Revises: c0ea77b7f629
Create Date: 2020-01-06 19:36:40.314911

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1edf57319173'
down_revision = 'c0ea77b7f629'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION HSTORE')
    op.add_column('child', sa.Column('bio_summary_translations', postgresql.HSTORE(text_type=sa.Text()), nullable=True))
    op.add_column('child', sa.Column('bio_translations', postgresql.HSTORE(text_type=sa.Text()), nullable=True))
    op.add_column('child', sa.Column('sayname_translations', postgresql.HSTORE(text_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('child', 'sayname_translations')
    op.drop_column('child', 'bio_translations')
    op.drop_column('child', 'bio_summary_translations')
    # ### end Alembic commands ###
