"""empty message

Revision ID: 1f016532ea43
Revises: 3f2709228571
Create Date: 2020-08-09 01:42:44.281211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f016532ea43'
down_revision = '3f2709228571'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('''
        ALTER TABLE invitations ALTER COLUMN text TYPE character varying(512);
    ''')
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
