"""Index jti

Revision ID: 205979e02b2d
Revises: 1d93da5f70f7
Create Date: 2020-02-10 02:23:06.062311

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = '205979e02b2d'
down_revision = '56a3abfdf12b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('COMMIT')

    op.create_index(
        op.f('revoked_tokens_jti_idx'),
        'revoked_tokens',
        ['jti'],
        postgresql_concurrently=True,
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('revoked_tokens_jti_idx'), table_name='revoked_tokens')
    # ### end Alembic commands ###
