"""empty message

Revision ID: 2bd28fcb77ec
Revises: 3a1a0f992985
Create Date: 2020-01-13 17:14:50.054605

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op


# revision identifiers, used by Alembic.
revision = '2bd28fcb77ec'
down_revision = '3a1a0f992985'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'payment',
        'track_id',
        new_column_name='gateway_track_id',
    )

    op.alter_column(
        'payment',
        'orderId',
        new_column_name='order_id',
    )

    op.alter_column(
        'payment',
        'donate',
        new_column_name='donation_amount',
    )

    op.alter_column(
        'payment',
        'amount',
        new_column_name='need_amount',
    )

    op.alter_column(
        'payment',
        'paymentId',
        new_column_name='gateway_payment_id',
    )

    op.alter_column(
        'payment',
        'date',
        new_column_name='transaction_date',
    )

    op.add_column(
        'payment',
        sa.Column('credit_amount', sa.Integer(), nullable=True),
    )

    op.add_column(
        'payment',
        sa.Column('use_credit', sa.Boolean(), nullable=False, server_default='False'),
    )

    op.add_column('payment', sa.Column('verified', sa.DateTime(), nullable=True))
    op.execute('UPDATE payment SET verified = transaction_date;')

    op.drop_column('payment', 'verfied_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'payment',
        sa.Column(
            'verfied_date',
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        'payment',
        sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.add_column(
        'payment',
        sa.Column('paymentId', sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        'payment',
        sa.Column(
            'donate',
            sa.INTEGER(),
            server_default=sa.text('0'),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        'payment', sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.add_column(
        'payment',
        sa.Column(
            'date',
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        'payment',
        sa.Column('orderId', sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        'payment',
        sa.Column('track_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column('payment', 'verified')
    op.drop_column('payment', 'use_credit')
    op.drop_column('payment', 'transaction_date')
    op.drop_column('payment', 'order_id')
    op.drop_column('payment', 'need_amount')
    op.drop_column('payment', 'gateway_track_id')
    op.drop_column('payment', 'gateway_payment_id')
    op.drop_column('payment', 'donation_amount')
    op.drop_column('payment', 'credit_amount')
    # ### end Alembic commands ###
