"""empty message

Revision ID: 3351aaef2c7e
Revises: 37b19dbb4242
Create Date: 2020-11-13 03:52:11.188664

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op


# revision identifiers, used by Alembic.
revision = '3351aaef2c7e'
down_revision = '37b19dbb4242'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'need_family', sa.Column('address', sa.Unicode(length=64), nullable=True)
    )
    op.create_foreign_key(
        op.f('need_family_address_nakama_owners_fkey'),
        'need_family',
        'nakama_owners',
        ['address'],
        ['address'],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f('need_family_address_nakama_owners_fkey'),
        'need_family',
        type_='foreignkey',
    )
    op.drop_column('need_family', 'address')
    # ### end Alembic commands ###
