"""Removed not null on coordinator id from ngo

Revision ID: 3868cd9f04f2
Revises: 1f016532ea43
Create Date: 2020-08-13 16:00:12.508114

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = '3868cd9f04f2'
down_revision = '1f016532ea43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ngo', 'coordinatorId', existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ngo', 'coordinatorId', existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
