"""empty message

Revision ID: 3b76dac2c5a7
Revises: 04db12d9fe52
Create Date: 2022-01-06 14:29:13.859100

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = '3b76dac2c5a7'
down_revision = '04db12d9fe52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'social_worker', sa.Column('is_coordinator', sa.Boolean(), nullable=True)
    )
    op.execute(
        '''
        UPDATE social_worker set is_coordinator = false;
    '''
    )

    op.execute(
        '''
        UPDATE social_worker set is_coordinator = true where id in (select "coordinatorId" from ngo where "coordinatorId" is not null);
    '''
    )
    op.execute('''alter table social_worker alter COLUMN is_coordinator set not null;''')

    op.drop_constraint('ngo_coordinatorId_social_worker_fkey', 'ngo', type_='foreignkey')
    op.drop_column('ngo', 'coordinatorId')
    op.drop_column('social_worker', 'need_count')
    op.drop_column('social_worker', 'current_need_count')
    op.add_column(
        'social_worker_version',
        sa.Column('is_coordinator', sa.Boolean(), autoincrement=False, nullable=True),
    )
    op.drop_column('social_worker_version', 'need_count')
    op.drop_column('social_worker_version', 'current_need_count')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'social_worker_version',
        sa.Column('current_need_count', sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        'social_worker_version',
        sa.Column('need_count', sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_column('social_worker_version', 'is_coordinator')
    op.add_column(
        'social_worker',
        sa.Column(
            'current_need_count',
            sa.INTEGER(),
            server_default=sa.text('0'),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        'social_worker',
        sa.Column(
            'need_count',
            sa.INTEGER(),
            server_default=sa.text('0'),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column('social_worker', 'is_coordinator')
    op.add_column(
        'ngo',
        sa.Column('coordinatorId', sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        'ngo_coordinatorId_social_worker_fkey',
        'ngo',
        'social_worker',
        ['coordinatorId'],
        ['id'],
    )
    ### end Alembic commands ###
