"""empty message

Revision ID: 3f2709228571
Revises: 8c086c49971c
Create Date: 2020-08-09 01:41:30.057910

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = '3f2709228571'
down_revision = '8c086c49971c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('revoked_tokens_jti_idx', table_name='revoked_tokens')
    op.drop_table('revoked_tokens')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'revoked_tokens',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('jti', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint('id', name='revoked_tokens_pkey'),
    )
    op.create_index('revoked_tokens_jti_idx', 'revoked_tokens', ['jti'], unique=False)
    # ### end Alembic commands ###
