"""empty message

Revision ID: 47dfd9091cb4
Revises: 6f2dd2e41771
Create Date: 2021-12-08 17:58:28.151138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47dfd9091cb4'
down_revision = '6f2dd2e41771'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('social_worker', 'lastLogoutDate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_worker', sa.Column('lastLogoutDate', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
