"""Added bank_track_id to need

Revision ID: 4890d13e6493
Revises: e068d4d08af7
Create Date: 2020-02-25 19:59:07.883498

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = '4890d13e6493'
down_revision = 'e068d4d08af7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('need', sa.Column('bank_track_id', sa.Unicode(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('need', 'bank_track_id')
    # ### end Alembic commands ###
