"""empty message

Revision ID: 4b9467b1d61a
Revises: 6616bfd81819
Create Date: 2020-06-03 22:21:58.762420

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = '4b9467b1d61a'
down_revision = '6616bfd81819'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'change_cost',
        sa.Column('created', sa.DateTime(), nullable=False),
        sa.Column('updated', sa.DateTime(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('need_id', sa.Integer(), nullable=False),
        sa.Column('requester_id', sa.Integer(), nullable=False),
        sa.Column('reviewer_id', sa.Integer(), nullable=True),
        sa.Column(
            'status',
            sa.Enum('pending', 'accepted', 'rejected', name='changecoststatus'),
            nullable=True,
        ),
        sa.Column('from_', sa.Integer(), nullable=False),
        sa.Column('to', sa.Integer(), nullable=False),
        sa.Column('description', sa.String(length=128), nullable=False),
        sa.Column('reject_cause', sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(
            ['need_id'], ['need.id'], name=op.f('change_cost_need_id_need_fkey')
        ),
        sa.ForeignKeyConstraint(
            ['requester_id'],
            ['social_worker.id'],
            name=op.f('change_cost_requester_id_social_worker_fkey'),
        ),
        sa.ForeignKeyConstraint(
            ['reviewer_id'],
            ['social_worker.id'],
            name=op.f('change_cost_reviewer_id_social_worker_fkey'),
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('change_cost_pkey')),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('change_cost')
    # ### end Alembic commands ###
