"""empty message

Revision ID: 4bddeb43ad25
Revises: 7a188caf39ff
Create Date: 2022-04-05 17:34:39.143586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bddeb43ad25'
down_revision = '7a188caf39ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('states', sa.Column('state_code', sa.Unicode(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('states', 'state_code')
    # ### end Alembic commands ###
