"""empty message

Revision ID: 4f6c866b9951
Revises: 6616bfd81819
Create Date: 2020-06-09 15:08:07.946992

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = '4f6c866b9951'
down_revision = '6616bfd81819'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('need', sa.Column('unavailable_from', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('need', 'unavailable_from')
    # ### end Alembic commands ###
