"""empty message

Revision ID: 5637c5fe8dca
Revises: 28d2e4c9af84
Create Date: 2020-01-18 15:11:48.756211

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = '5637c5fe8dca'
down_revision = '28d2e4c9af84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment', 'id_need', existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment', 'id_need', existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
