"""empty message

Revision ID: 56a3abfdf12b
Revises: 98472bc803ca
Create Date: 2020-02-08 19:41:27.111954

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op


# revision identifiers, used by Alembic.
revision = '56a3abfdf12b'
down_revision = '98472bc803ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'child_migration',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('child_id', sa.Integer(), nullable=False),
        sa.Column('new_sw_id', sa.Integer(), nullable=False),
        sa.Column('old_sw_id', sa.Integer(), nullable=False),
        sa.Column('new_generated_code', sa.String(), nullable=False),
        sa.Column('old_generated_code', sa.String(), nullable=False),
        sa.Column('migrated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ['child_id'], ['child.id'], name=op.f('child_migration_child_id_child_fkey')
        ),
        sa.ForeignKeyConstraint(
            ['new_sw_id'],
            ['social_worker.id'],
            name=op.f('child_migration_new_sw_id_social_worker_fkey'),
        ),
        sa.ForeignKeyConstraint(
            ['old_sw_id'],
            ['social_worker.id'],
            name=op.f('child_migration_old_sw_id_social_worker_fkey'),
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('child_migration_pkey')),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('child_migration')
    # ### end Alembic commands ###
