"""empty message

Revision ID: 577a9b1b8182
Revises: 1af0eb7a1038
Create Date: 2020-01-07 21:27:55.498868

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = '577a9b1b8182'
down_revision = '1af0eb7a1038'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''update child set sayname_translations = hstore('en', "sayName") || hstore('fa', "sayName_fa");'''
    )
    op.execute(
        '''update child set bio_translations = hstore('en', bio) || hstore('fa', bio_fa);'''
    )
    op.execute(
        '''update child set bio_summary_translations = hstore('en', "bioSummary") || hstore('fa', "bioSummary_fa");'''
    )

    op.execute(
        '''update need set name_translations = hstore('en', name) || hstore('fa', name_fa);'''
    )
    op.execute(
        '''update need set description_translations = hstore('en', description) || hstore('fa', description_fa);'''
    )
    op.execute(
        '''update need set description_summary_translations = hstore('en', "descriptionSummary") || hstore('fa', "descriptionSummary_fa");'''
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
