"""empty message

Revision ID: 581a6749804a
Revises: 1c9723a01057
Create Date: 2021-08-24 19:21:09.710269

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = '581a6749804a'
down_revision = '1c9723a01057'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE receipt set title = 'No Title';")
    op.alter_column(
        'receipt', 'code', existing_type=sa.VARCHAR(length=128), nullable=True
    )
    op.alter_column(
        'receipt', 'title', existing_type=sa.VARCHAR(length=128), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'receipt', 'title', existing_type=sa.VARCHAR(length=128), nullable=True
    )
    op.alter_column(
        'receipt', 'code', existing_type=sa.VARCHAR(length=128), nullable=False
    )
    # ### end Alembic commands ###
