"""empty message

Revision ID: 654453a18f24
Revises: 6bbd22f95d40
Create Date: 2021-04-26 12:09:44.127744

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = '654453a18f24'
down_revision = '6bbd22f95d40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f('child_existence_status_idx'), 'child', ['existence_status'], unique=False
    )
    op.create_index(
        op.f('child_generatedCode_idx'), 'child', ['generatedCode'], unique=False
    )
    op.create_index(op.f('child_isDeleted_idx'), 'child', ['isDeleted'], unique=False)
    op.create_index(op.f('child_isMigrated_idx'), 'child', ['isMigrated'], unique=False)
    op.create_index(op.f('child_migratedId_idx'), 'child', ['migratedId'], unique=False)
    op.create_index(op.f('need_isConfirmed_idx'), 'need', ['isConfirmed'], unique=False)
    op.create_index(op.f('need_isDeleted_idx'), 'need', ['isDeleted'], unique=False)
    op.create_index(op.f('need_isReported_idx'), 'need', ['isReported'], unique=False)
    op.create_index(
        op.f('need_oncePurchased_idx'), 'need', ['oncePurchased'], unique=False
    )
    op.create_index(op.f('need_status_idx'), 'need', ['status'], unique=False)
    op.create_index(op.f('need_type_idx'), 'need', ['type'], unique=False)
    op.create_index(
        op.f('need_family_isDeleted_idx'), 'need_family', ['isDeleted'], unique=False
    )
    op.create_index(op.f('payment_verified_idx'), 'payment', ['verified'], unique=False)
    op.create_index(
        op.f('social_worker_isDeleted_idx'),
        'social_worker',
        ['isDeleted'],
        unique=False,
    )
    op.create_index(
        op.f('user_is_email_verified_idx'), 'user', ['is_email_verified'], unique=False
    )
    op.create_index(op.f('user_is_nakama_idx'), 'user', ['is_nakama'], unique=False)
    op.create_index(
        op.f('user_is_phonenumber_verified_idx'),
        'user',
        ['is_phonenumber_verified'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('user_is_phonenumber_verified_idx'), table_name='user')
    op.drop_index(op.f('user_is_nakama_idx'), table_name='user')
    op.drop_index(op.f('user_is_email_verified_idx'), table_name='user')
    op.drop_index(op.f('social_worker_isDeleted_idx'), table_name='social_worker')
    op.drop_index(op.f('payment_verified_idx'), table_name='payment')
    op.drop_index(op.f('need_family_isDeleted_idx'), table_name='need_family')
    op.drop_index(op.f('need_type_idx'), table_name='need')
    op.drop_index(op.f('need_status_idx'), table_name='need')
    op.drop_index(op.f('need_oncePurchased_idx'), table_name='need')
    op.drop_index(op.f('need_isReported_idx'), table_name='need')
    op.drop_index(op.f('need_isDeleted_idx'), table_name='need')
    op.drop_index(op.f('need_isConfirmed_idx'), table_name='need')
    op.drop_index(op.f('child_migratedId_idx'), table_name='child')
    op.drop_index(op.f('child_isMigrated_idx'), table_name='child')
    op.drop_index(op.f('child_isDeleted_idx'), table_name='child')
    op.drop_index(op.f('child_generatedCode_idx'), table_name='child')
    op.drop_index(op.f('child_existence_status_idx'), table_name='child')
    # ### end Alembic commands ###
