"""empty message

Revision ID: 6616bfd81819
Revises: a7f15f27dc62
Create Date: 2020-05-07 01:00:23.400607

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = '6616bfd81819'
down_revision = 'a7f15f27dc62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('see_count', sa.Integer(), nullable=True))
    op.execute('UPDATE invitations set see_count = 0;')
    op.execute('ALTER TABLE invitations ALTER COLUMN see_count SET NOT NULL;')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invitations', 'see_count')
    # ### end Alembic commands ###
