"""empty message

Revision ID: 688d75aed5b3
Revises: 7583d200b34a
Create Date: 2021-11-19 23:20:59.520934

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = '688d75aed5b3'
down_revision = '7583d200b34a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    from say.models import User
    from say.orm import init_model
    from say.orm import session

    init_model(op.get_bind())

    conn = op.get_bind()
    user_avatars = conn.execute("""SELECT id, "avatarUrl" from "user";""").fetchall()

    all_users = session.query(User)
    total_count = all_users.count()
    print(f'Migration user avatars, total count: {total_count}')
    for i, user in enumerate(all_users):
        print(f'#{i}/{total_count}, user avatar #{user.id}')
        raw_user = list(filter(lambda u: u[0] == user.id, user_avatars))[0]
        avatar = raw_user[1]

        if (
            avatar is None
            or avatar == ''
            or avatar == '/public/resources/img/default-avatar.png'
        ):
            user.avatarUrl = None
            continue

    session.commit()
    op.create_unique_constraint(op.f('user_avatarUrl_key'), 'user', ['avatarUrl'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_avatarUrl_key'), 'user', type_='unique')
    # ### end Alembic commands ###
