"""empty message

Revision ID: 68cdc5cf713e
Revises: 763f95d78e42
Create Date: 2021-12-14 17:49:11.558720

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = '68cdc5cf713e'
down_revision = '763f95d78e42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'social_worker',
        'generatedCode',
        new_column_name='generated_code',
    )
    op.alter_column(
        'social_worker',
        'id_ngo',
        new_column_name='ngo_id',
    )
    op.alter_column(
        'social_worker',
        'id_type',
        new_column_name='type_id',
    )
    op.alter_column(
        'social_worker',
        'firstName',
        new_column_name='first_name',
    )
    op.alter_column(
        'social_worker',
        'lastName',
        new_column_name='last_name',
    )
    op.alter_column(
        'social_worker',
        'userName',
        new_column_name='username',
    )
    op.alter_column(
        'social_worker',
        'birthCertificateNumber',
        new_column_name='birth_certificate_number',
    )
    op.alter_column(
        'social_worker',
        'idNumber',
        new_column_name='id_number',
    )
    op.alter_column(
        'social_worker',
        'idCardUrl',
        new_column_name='id_card_url',
    )
    op.alter_column(
        'social_worker',
        'passportNumber',
        new_column_name='passport_number',
    )
    op.alter_column(
        'social_worker',
        'passportUrl',
        new_column_name='passport_url',
    )
    op.alter_column(
        'social_worker',
        'birthDate',
        new_column_name='birth_date',
    )
    op.alter_column(
        'social_worker',
        'phoneNumber',
        new_column_name='phone_number',
    )
    op.alter_column(
        'social_worker',
        'emergencyPhoneNumber',
        new_column_name='emergency_phone_number',
    )
    op.alter_column(
        'social_worker',
        'emailAddress',
        new_column_name='email',
    )
    op.alter_column(
        'social_worker',
        'telegramId',
        new_column_name='telegram_id',
    )
    op.alter_column(
        'social_worker',
        'postalAddress',
        new_column_name='postal_address',
    )
    op.alter_column(
        'social_worker',
        'avatarUrl',
        new_column_name='avatar_url',
    )
    op.alter_column(
        'social_worker',
        'needCount',
        new_column_name='need_count',
    )
    op.alter_column(
        'social_worker',
        'currentNeedCount',
        new_column_name='current_need_count',
    )
    op.alter_column(
        'social_worker',
        'bankAccountNumber',
        new_column_name='bank_account_number',
    )
    op.alter_column(
        'social_worker',
        'bankAccountShebaNumber',
        new_column_name='bank_account_sheba_number',
    )
    op.alter_column(
        'social_worker',
        'bankAccountCardNumber',
        new_column_name='bank_account_card_number',
    )
    op.alter_column(
        'social_worker',
        'lastLoginDate',
        new_column_name='last_login_date',
    )
    op.alter_column(
        'social_worker',
        'isDeleted',
        new_column_name='is_deleted',
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'social_worker',
        'generated_code',
        new_column_name='generatedCode',
    )
    # ### end Alembic commands ###
