"""empty message

Revision ID: 6a51baa0e0d9
Revises: adbc4f3af072
Create Date: 2021-12-07 10:42:39.089585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a51baa0e0d9'
down_revision = 'adbc4f3af072'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ngo', 'childrenCount')
    op.drop_column('ngo', 'socialWorkerCount')
    op.drop_column('ngo', 'currentSocialWorkerCount')
    op.drop_column('ngo', 'currentChildrenCount')
    op.create_unique_constraint(op.f('social_worker_userName_key'), 'social_worker', ['userName'])
    op.drop_column('social_worker', 'registerDate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_worker', sa.Column('registerDate', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('social_worker_userName_key'), 'social_worker', type_='unique')
    op.add_column('ngo', sa.Column('currentChildrenCount', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('ngo', sa.Column('currentSocialWorkerCount', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('ngo', sa.Column('socialWorkerCount', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('ngo', sa.Column('childrenCount', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
