"""Add deleted_at and unconfirm_at to need

Revision ID: 6b49c131765d
Revises: 893aa96e499e
Create Date: 2021-09-08 15:37:09.401221

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = '6b49c131765d'
down_revision = '893aa96e499e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('need', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('need', sa.Column('unconfirmed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('need', 'unconfirmed_at')
    op.drop_column('need', 'deleted_at')
    # ### end Alembic commands ###
