"""empty message

Revision ID: 6d3d0ec12513
Revises: 205979e02b2d
Create Date: 2020-02-10 17:52:01.907190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d3d0ec12513'
down_revision = '205979e02b2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('need_family', 'id_user',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('nextval(\'"need_family_Id_user_seq"\'::regclass)'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('need_family', 'id_user',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('nextval(\'"need_family_Id_user_seq"\'::regclass)'))
    # ### end Alembic commands ###
