"""empty message

Revision ID: 6d4d1b58534f
Revises: 2bd28fcb77ec
Create Date: 2020-01-13 20:54:36.220393

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = '6d4d1b58534f'
down_revision = '2bd28fcb77ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE child RENAME COLUMN "spentCredit" TO spent_credit')
    op.drop_column('payment', 'is_verified')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'payment',
        sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
