"""Change lastlogin to datetime

Revision ID: 6e69d8ab1ad2
Revises: 031739cac62c
Create Date: 2020-02-23 20:49:22.447904

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = '6e69d8ab1ad2'
down_revision = '031739cac62c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'user',
        'lastLogin',
        type_=sa.DateTime,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'lastLogin', type_=sa.Date, nullable=False)
    # ### end Alembic commands ###
