"""empty message

Revision ID: 6f2dd2e41771
Revises: 1a333a9886a1
Create Date: 2021-12-08 17:22:47.861370

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = '6f2dd2e41771'
down_revision = '1a333a9886a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """ALTER TABLE social_worker ADD COLUMN time_holder TIMESTAMP without time zone NULL;"""
    )
    op.execute("""UPDATE social_worker SET time_holder = "lastLoginDate"::TIMESTAMP;""")
    op.execute(
        """ALTER TABLE social_worker ALTER COLUMN "lastLoginDate" TYPE TIMESTAMP without time zone USING time_holder;"""
    )

    op.execute("""ALTER TABLE social_worker DROP COLUMN time_holder;""")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
