"""empty message

Revision ID: 71c546a8c3c3
Revises: 19bc90e76676
Create Date: 2022-04-10 12:12:28.501170

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = '71c546a8c3c3'
down_revision = '19bc90e76676'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ngo', 'city_id', existing_type=sa.INTEGER(), nullable=False)
    op.drop_column('ngo', 'city')
    op.drop_column('ngo', 'country')
    op.drop_column('social_worker', 'city')
    op.drop_column('social_worker', 'country')
    op.drop_column('social_worker_version', 'city')
    op.drop_column('social_worker_version', 'country')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'social_worker_version',
        sa.Column('country', sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        'social_worker_version',
        sa.Column('city', sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        'social_worker',
        sa.Column('country', sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        'social_worker',
        sa.Column('city', sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        'ngo', sa.Column('country', sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.add_column(
        'ngo', sa.Column('city', sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.alter_column('ngo', 'city_id', existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
