"""empty message

Revision ID: 726989d63e15
Revises: e1ad3d68003e
Create Date: 2020-04-21 13:14:59.483410

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = '726989d63e15'
down_revision = 'e1ad3d68003e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitations',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.Column('token', sa.Unicode(length=128), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['family.id'], name=op.f('invitations_family_id_family_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('invitations_pkey'))
    )
    op.execute('COMMIT')
    op.create_index(
        op.f('invitations_token_idx'),
        'invitations',
        ['token'],
        unique=True,
        postgresql_concurrently=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('invitations_token_idx'), table_name='invitations')
    op.drop_table('invitations')
    # ### end Alembic commands ###
