"""empty message

Revision ID: 73d8303ffae0
Revises: 9b39c99f9f44
Create Date: 2020-04-24 00:12:57.784912

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = '73d8303ffae0'
down_revision = '9b39c99f9f44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('postal_address', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('postal_code', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'postal_code')
    op.drop_column('user', 'postal_address')
    # ### end Alembic commands ###
