"""empty message

Revision ID: 763f95d78e42
Revises: cf604eb4dc19
Create Date: 2021-12-11 22:14:46.979458

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = '763f95d78e42'
down_revision = 'cf604eb4dc19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'base_users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('type', sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('base_users_pkey')),
    )

    op.execute(
        '''
        INSERT INTO base_users (id, type) SELECT id, 'social_worker' FROM social_worker;
        '''
    )

    op.execute(
        '''
        INSERT INTO base_users (id, type) SELECT id, 'user' FROM "user";
        '''
    )

    op.execute('ALTER SEQUENCE base_users_id_seq RESTART WITH 12000;')

    op.create_foreign_key(
        op.f('social_worker_id_base_users_fkey'),
        'social_worker',
        'base_users',
        ['id'],
        ['id'],
    )
    op.drop_constraint(
        'transaction_user_id_social_worker_fkey', 'transaction', type_='foreignkey'
    )
    op.create_foreign_key(
        op.f('transaction_user_id_base_users_fkey'),
        'transaction',
        'base_users',
        ['user_id'],
        ['id'],
    )
    op.create_foreign_key(
        op.f('user_id_base_users_fkey'), 'user', 'base_users', ['id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_id_base_users_fkey'), 'user', type_='foreignkey')
    op.drop_constraint(
        op.f('transaction_user_id_base_users_fkey'), 'transaction', type_='foreignkey'
    )
    op.create_foreign_key(
        'transaction_user_id_social_worker_fkey',
        'transaction',
        'social_worker',
        ['user_id'],
        ['id'],
    )
    op.drop_constraint(
        op.f('social_worker_id_base_users_fkey'), 'social_worker', type_='foreignkey'
    )
    op.drop_table('base_users')
    # ### end Alembic commands ###
