"""empty message

Revision ID: 792e0cebae00
Revises: 133ac22dd633
Create Date: 2020-01-27 14:44:40.845243

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = '792e0cebae00'
down_revision = '133ac22dd633'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'reset_password',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('token', sa.String(), nullable=False),
        sa.Column('expire_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ['user_id'], ['user.id'], name=op.f('reset_password_user_id_user_fkey')
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('reset_password_pkey')),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reset_password')
    # ### end Alembic commands ###
