"""empty message

Revision ID: 79dca1f060ba
Revises: a8268ff1ea6b
Create Date: 2020-07-29 00:12:35.427541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79dca1f060ba'
down_revision = 'a8268ff1ea6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('UPDATE "user" SET "avatarUrl" = \'public/resources/img/default-avatar.png\' WHERE "avatarUrl" is NULL')
    op.alter_column('user', 'avatarUrl',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'avatarUrl',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
