"""empty message

Revision ID: 869ac90670f6
Revises: 45f03610162c
Create Date: 2022-04-05 17:40:28.648658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '869ac90670f6'
down_revision = '45f03610162c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('wikidataid', sa.Unicode(length=255), nullable=True))
    op.drop_column('cities', 'wikiDataId')
    op.add_column('countries', sa.Column('wikidataid', sa.Unicode(length=255), nullable=True))
    op.drop_column('countries', 'wikiDataId')
    op.add_column('states', sa.Column('wikidataid', sa.Unicode(length=255), nullable=True))
    op.drop_column('states', 'wikiDataId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('states', sa.Column('wikiDataId', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('states', 'wikidataid')
    op.add_column('countries', sa.Column('wikiDataId', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('countries', 'wikidataid')
    op.add_column('cities', sa.Column('wikiDataId', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('cities', 'wikidataid')
    # ### end Alembic commands ###
