"""empty message

Revision ID: 8713162b738f
Revises: 091009b644e8
Create Date: 2019-12-31 18:12:15.924175

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = '8713162b738f'
down_revision = '091009b644e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('child', sa.Column('bioSummary_fa', sa.Text(), nullable=True))
    op.add_column('child', sa.Column('bio_fa', sa.Text(), nullable=True))
    op.add_column('child', sa.Column('sayName_fa', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('child', 'sayName_fa')
    op.drop_column('child', 'bio_fa')
    op.drop_column('child', 'bioSummary_fa')
    # ### end Alembic commands ###
