"""empty message

Revision ID: 8c086c49971c
Revises: b5d961ee562e
Create Date: 2020-08-08 02:15:39.144842

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = '8c086c49971c'
down_revision = 'b5d961ee562e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitation_accepts', sa.Column('role', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invitation_accepts', 'role')
    # ### end Alembic commands ###
