"""Added email index

Revision ID: a1863d77ffa0
Revises: 19967d98dbb1
Create Date: 2020-03-11 19:59:46.438049

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = 'a1863d77ffa0'
down_revision = '19967d98dbb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('COMMIT')

    op.create_index(
        op.f('user_emailAddress_idx'),
        'user',
        ['emailAddress'],
        postgresql_concurrently=True,
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
