"""empty message

Revision ID: a426c0feff72
Revises: 6c29876e4902
Create Date: 2020-01-15 23:14:48.257972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a426c0feff72'
down_revision = '6c29876e4902'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE "user" RENAME COLUMN "doneNeedCount" TO done_needs_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE "user" RENAME COLUMN done_needs_count TO doneNeedsCount')
    # ### end Alembic commands ###
