"""empty message

Revision ID: ad7e3b4a98cf
Revises: ce24c78ee6c8
Create Date: 2020-09-01 12:59:12.350983

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = 'ad7e3b4a98cf'
down_revision = 'ce24c78ee6c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'avatarUrl',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'avatarUrl',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
