"""empty message

Revision ID: b4d388c3cfca
Revises: 92e7bd6272b0
Create Date: 2021-11-11 23:54:23.216092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4d388c3cfca'
down_revision = '92e7bd6272b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'flagUrl')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('flagUrl', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
