"""empty message

Revision ID: b5d961ee562e
Revises: 1324530cace6
Create Date: 2020-08-08 01:52:57.780430

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = 'b5d961ee562e'
down_revision = '1324530cace6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'invitation_accepts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('invtee_id', sa.Integer(), nullable=False),
        sa.Column('invitation_id', sa.Integer(), nullable=False),
        sa.Column('created', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ['invitation_id'],
            ['invitations.id'],
            name=op.f('invitation_accepts_invitation_id_invitations_fkey'),
        ),
        sa.ForeignKeyConstraint(
            ['invtee_id'],
            ['user.id'],
            name=op.f('invitation_accepts_invtee_id_user_fkey'),
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('invitation_accepts_pkey')),
    )
    op.create_index(
        op.f('invitation_accepts_invitation_id_idx'),
        'invitation_accepts',
        ['invitation_id'],
        unique=False,
    )
    op.create_index(
        op.f('invitation_accepts_invtee_id_idx'),
        'invitation_accepts',
        ['invtee_id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('invitation_accepts_invtee_id_idx'), table_name='invitation_accepts'
    )
    op.drop_index(
        op.f('invitation_accepts_invitation_id_idx'), table_name='invitation_accepts'
    )
    op.drop_table('invitation_accepts')
    # ### end Alembic commands ###
