"""empty message

Revision ID: c0eb2faca9f7
Revises: e711ed496efc
Create Date: 2021-12-10 15:02:09.114021

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = 'c0eb2faca9f7'
down_revision = 'e711ed496efc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        ALTER TABLE social_worker
        RENAME COLUMN "isActive" TO is_active;'''
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        ALTER TABLE social_worker
        RENAME COLUMN is_active TO "isActive";'''
    )
    # ### end Alembic commands ###
