"""empty message

Revision ID: c242455d454b
Revises: 9b05b9b45ab0
Create Date: 2020-11-13 03:11:26.427852

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op


# revision identifiers, used by Alembic.
revision = 'c242455d454b'
down_revision = '9b05b9b45ab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('is_nakama', sa.Boolean(), nullable=True))
    op.execute('UPDATE payment set is_nakama = false;')
    op.execute('ALTER TABLE payment ALTER COLUMN is_nakama SET NOT NULL;')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'is_nakama')
    # ### end Alembic commands ###
