"""empty message

Revision ID: c24e93487fbf
Revises: 71c546a8c3c3
Create Date: 2022-05-29 15:56:40.411414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c24e93487fbf'
down_revision = '71c546a8c3c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipt', sa.Column('need_status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipt', 'need_status')
    # ### end Alembic commands ###
