"""empty message

Revision ID: d7af0041fbf7
Revises: dc4a116c9ef0
Create Date: 2021-09-16 14:34:25.782417

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = 'd7af0041fbf7'
down_revision = 'dc4a116c9ef0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_worker', sa.Column('_password', sa.String(length=256)))
    op.execute("UPDATE social_worker SET _password = '';")
    op.execute('ALTER TABLE social_worker ALTER COLUMN _password SET NOT NULL;')
    op.drop_column('social_worker', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'social_worker',
        sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column('social_worker', '_password')
    # ### end Alembic commands ###
