"""empty message

Revision ID: dcd67bb537e2
Revises: 5f88cc67b8d4
Create Date: 2020-02-18 16:58:32.630162

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = 'dcd67bb537e2'
down_revision = '5f88cc67b8d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('child', sa.Column('existence_status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('child', 'existence_status')
    # ### end Alembic commands ###
