"""empty message

Revision ID: ddfc2d0bb9b5
Revises: e057440bc359
Create Date: 2020-01-07 19:29:35.761770

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op


# revision identifiers, used by Alembic.
revision = 'ddfc2d0bb9b5'
down_revision = '1edf57319173'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'need',
        sa.Column(
            'description_summary_translations',
            postgresql.HSTORE(text_type=sa.Text()),
            nullable=True,
        ),
    )
    op.add_column(
        'need',
        sa.Column(
            'description_translations',
            postgresql.HSTORE(text_type=sa.Text()),
            nullable=True,
        ),
    )
    op.add_column(
        'need',
        sa.Column(
            'name_translations', postgresql.HSTORE(text_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('need', 'name_translations')
    op.drop_column('need', 'description_translations')
    op.drop_column('need', 'description_summary_translations')
    # ### end Alembic commands ###
