"""Added username and removed fullname in participants

Revision ID: e068d4d08af7
Revises: 2774278e1b7d
Create Date: 2020-02-25 16:18:55.225780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e068d4d08af7'
down_revision = '2774278e1b7d'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('need_family', sa.Column('username', sa.Text(), nullable=True))

    op.execute('''
        UPDATE need_family nf
        SET username = u."userName"
        FROM "user" u
        WHERE id_user = u.id;
    ''')

    op.execute('''
        ALTER TABLE need_family
        ALTER COLUMN username
        SET NOT NULL;
    ''')

    op.drop_column('need_family', 'user_fullname')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('need_family', sa.Column('user_fullname', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('need_family', 'username')
    # ### end Alembic commands ###
