"""empty message

Revision ID: e1ad3d68003e
Revises: 9b39c99f9f44
Create Date: 2020-04-21 13:02:27.558448

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = 'e1ad3d68003e'
down_revision = '9b39c99f9f44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.create_index(
            op.f('user_emailAddress_idx'), 'user', ['emailAddress'], unique=True
        )
    except:
        pass

    op.execute('COMMIT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('user_emailAddress_idx'), table_name='user')
    # ### end Alembic commands ###
