"""empty message

Revision ID: e711ed496efc
Revises: 47dfd9091cb4
Create Date: 2021-12-08 17:58:47.378526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e711ed496efc'
down_revision = '47dfd9091cb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_worker', sa.Column('lastLogoutDate', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('social_worker', 'lastLogoutDate')
    # ### end Alembic commands ###
