"""empty message

Revision ID: e71c915653f6
Revises: fa7d127f259b
Create Date: 2022-11-07 21:06:39.691799

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = 'e71c915653f6'
down_revision = 'fa7d127f259b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""ALTER TABLE "user" RENAME COLUMN city TO _city""")
    # op.add_column('user', sa.Column('_city', sa.Integer(), nullable=True))

    op.execute("""ALTER TABLE "user" RENAME COLUMN country TO _country""")
    # op.add_column('user', sa.Column('_country', sqlalchemy_utils.types.country.CountryType(length=2), nullable=True))

    op.add_column('user', sa.Column('city_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('user_city_id_cities_fkey'), 'user', 'cities', ['city_id'], ['id'])

    op.execute("""ALTER TABLE user_version RENAME COLUMN city TO _city""")
    op.execute("""ALTER TABLE user_version RENAME COLUMN city_mod TO _city_mod""")
    op.execute("""ALTER TABLE user_version RENAME COLUMN country TO _country""")
    op.execute("""ALTER TABLE user_version RENAME COLUMN country_mod TO _country_mod""")
    op.add_column('user_version', sa.Column('city_id', sa.Integer(), autoincrement=False, nullable=True))
    op.add_column('user_version', sa.Column('city_id_mod', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.drop_column('user_version', 'birthPlace_mod')
    op.drop_column('user_version', 'birthPlace')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_version', sa.Column('city', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_version', sa.Column('birthPlace', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_version', sa.Column('country', sa.VARCHAR(length=2), autoincrement=False, nullable=True))
    op.add_column('user_version', sa.Column('city_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('user_version', sa.Column('country_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('user_version', sa.Column('birthPlace_mod', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('user_version', 'city_id_mod')
    op.drop_column('user_version', 'city_id')
    op.drop_column('user_version', '_country_mod')
    op.drop_column('user_version', '_country')
    op.drop_column('user_version', '_city_mod')
    op.drop_column('user_version', '_city')
    op.add_column('user', sa.Column('birthPlace', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('city', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('country', sa.VARCHAR(length=8), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('user_city_id_cities_fkey'), 'user', type_='foreignkey')
    op.drop_column('user', 'city_id')
    op.drop_column('user', '_country')
    op.drop_column('user', '_city')
    # ### end Alembic commands ###
