"""empty message

Revision ID: ed298c4f0cf1
Revises: 869ac90670f6
Create Date: 2022-04-05 17:40:52.383850

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ed298c4f0cf1'
down_revision = '869ac90670f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cities', 'flag',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.alter_column('cities', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cities', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('cities', 'flag',
               existing_type=sa.SMALLINT(),
               nullable=False)
    # ### end Alembic commands ###
