"""empty message

Revision ID: f145097abf98
Revises: fe214bd981c5
Create Date: 2021-06-09 16:51:38.022745

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = 'f145097abf98'
down_revision = 'fe214bd981c5'
branch_labels = None
depends_on = None


def create_cart_for_users():
    from say.models import Cart
    from say.models import User
    from say.orm import init_model
    from say.orm import session

    init_model(op.get_bind())

    for user in session.query(User):
        session.add(Cart(user=user))

    session.commit()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'cart',
        sa.Column('created', sa.DateTime(), nullable=False),
        sa.Column('updated', sa.DateTime(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['user_id'], ['user.id'], name=op.f('cart_user_id_user_fkey')
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('cart_pkey')),
        sa.UniqueConstraint('user_id', name=op.f('cart_user_id_key')),
    )
    op.create_table(
        'cart_needs',
        sa.Column('updated', sa.DateTime(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('cart_id', sa.Integer(), nullable=False),
        sa.Column('need_id', sa.Integer(), nullable=False),
        sa.Column('created', sa.DateTime(), nullable=False),
        sa.Column('deleted', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ['cart_id'], ['cart.id'], name=op.f('cart_needs_cart_id_cart_fkey')
        ),
        sa.ForeignKeyConstraint(
            ['need_id'], ['need.id'], name=op.f('cart_needs_need_id_need_fkey')
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('cart_needs_pkey')),
    )
    op.create_index(
        op.f('cart_needs_cart_id_idx'), 'cart_needs', ['cart_id'], unique=False
    )
    op.create_index(
        op.f('cart_needs_need_id_idx'), 'cart_needs', ['need_id'], unique=False
    )

    create_cart_for_users()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('cart_needs_need_id_idx'), table_name='cart_needs')
    op.drop_index(op.f('cart_needs_cart_id_idx'), table_name='cart_needs')
    op.drop_table('cart_needs')
    op.drop_table('cart')
    # ### end Alembic commands ###
