"""empty message

Revision ID: f56b3f2e2f9a
Revises: eb1bff1a16e3
Create Date: 2020-08-07 22:24:30.612473

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = 'f56b3f2e2f9a'
down_revision = 'eb1bff1a16e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('inviter_id', sa.Integer(), nullable=True))
    op.create_index(op.f('invitations_family_id_idx'), 'invitations', ['family_id'], unique=False)
    op.create_index(op.f('invitations_inviter_id_idx'), 'invitations', ['inviter_id'], unique=False)
    op.create_foreign_key(op.f('invitations_inviter_id_user_fkey'), 'invitations', 'user', ['inviter_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('invitations_inviter_id_user_fkey'), 'invitations', type_='foreignkey')
    op.drop_index(op.f('invitations_inviter_id_idx'), table_name='invitations')
    op.drop_index(op.f('invitations_family_id_idx'), table_name='invitations')
    op.drop_column('invitations', 'inviter_id')
    # ### end Alembic commands ###
