"""empty message

Revision ID: f9a2e58b923c
Revises: 73d8303ffae0
Create Date: 2020-04-25 16:58:22.230482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9a2e58b923c'
down_revision = '73d8303ffae0'
branch_labels = None
depends_on = None


def upgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
#    op.drop_constraint('user_emailAddress_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
#   op.create_unique_constraint('user_emailAddress_key', 'user', ['emailAddress'])
    # ### end Alembic commands ###
