"""empty message

Revision ID: fd994736750c
Revises: ad7e3b4a98cf
Create Date: 2020-09-05 17:03:53.827108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd994736750c'
down_revision = 'ad7e3b4a98cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DELETE FROM reset_password;')
    op.create_index(op.f('reset_password_token_idx'), 'reset_password', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('reset_password_token_idx'), table_name='reset_password')
    # ### end Alembic commands ###
