"""empty message

Revision ID: 00feed0d5c61
Revises: ffe4e31a3ea7
Create Date: 2020-07-28 03:18:10.525032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00feed0d5c61'
down_revision = 'ffe4e31a3ea7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('accepted_at', sa.DateTime(), nullable=True))
    op.add_column('invitations', sa.Column('rejected_at', sa.DateTime(), nullable=True))
    op.add_column('invitations', sa.Column('rejected_reason', sa.Unicode(length=100), nullable=True))
    op.drop_index('invitations_token_idx', table_name='invitations')
    op.create_index(op.f('invitations_token_idx'), 'invitations', ['token'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('invitations_token_idx'), table_name='invitations')
    op.create_index('invitations_token_idx', 'invitations', ['token'], unique=True)
    op.drop_column('invitations', 'rejected_reason')
    op.drop_column('invitations', 'rejected_at')
    op.drop_column('invitations', 'accepted_at')
    # ### end Alembic commands ###
