"""empty message

Revision ID: 1af0eb7a1038
Revises: ddfc2d0bb9b5
Create Date: 2020-01-07 19:47:07.493941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1af0eb7a1038'
down_revision = 'ddfc2d0bb9b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('''
        ALTER TABLE need ALTER COLUMN name DROP NOT NULL;
    ''')
    op.execute('''
        ALTER TABLE need ALTER COLUMN "descriptionSummary" DROP NOT NULL;
    ''')
    op.execute('''
        ALTER TABLE need ALTER COLUMN description DROP NOT NULL;
    ''')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
