"""empty message

Revision ID: 2153402df074
Revises: 398f3fcb0980
Create Date: 2020-01-22 19:48:45.009028

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2153402df074'
down_revision = '398f3fcb0980'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('child', sa.Column('firstName_translations', postgresql.HSTORE(text_type=sa.Text()), nullable=True))
    op.add_column('child', sa.Column('lastName_translations', postgresql.HSTORE(text_type=sa.Text()), nullable=True))
    op.execute('''update child set "firstName_translations" = hstore('en', "firstName") || hstore('fa', "firstName_fa");''')
    op.execute('''update child set "lastName_translations" = hstore('en', "lastName") || hstore('fa', "lastName_fa");''')
    op.drop_column('child', 'firstName')
    op.drop_column('child', 'lastName_fa')
    op.drop_column('child', 'lastName')
    op.drop_column('child', 'firstName_fa')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('need', sa.Column('description_summary_translations', postgresql.HSTORE(text_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('child', sa.Column('firstName_fa', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('child', sa.Column('lastName', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('child', sa.Column('lastName_fa', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('child', sa.Column('firstName', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('child', 'lastName_translations')
    op.drop_column('child', 'firstName_translations')
    # ### end Alembic commands ###
