"""empty message

Revision ID: 27d7276b2d50
Revises: 819b92359559
Create Date: 2020-08-06 14:03:21.864454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27d7276b2d50'
down_revision = '819b92359559'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('text', sa.Unicode(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invitations', 'text')
    # ### end Alembic commands ###
