"""empty message

Revision ID: 5ac61af80282
Revises: 27d7276b2d50
Create Date: 2020-08-07 12:25:36.006813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ac61af80282'
down_revision = '27d7276b2d50'
branch_labels = None
depends_on = None


def upgrade():
    op.execute('''
        CREATE TYPE invitation_status AS ENUM ('pending', 'accepted', 'rejected');
        ALTER TABLE invitations DROP COLUMN status;
        ALTER TABLE invitations 
        ADD COLUMN status invitation_status default 'pending';
    ''')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
