"""Added phone_number and country

Revision ID: 5f6dcf3000eb
Revises: 884c1cd36094
Create Date: 2020-02-22 18:40:35.702216

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '5f6dcf3000eb'
down_revision = '884c1cd36094'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE "user" RENAME COLUMN country_code TO country')
    op.add_column('user', sa.Column('phone_number', sqlalchemy_utils.types.phone_number.PhoneNumberType(length=20), nullable=True))
    op.execute('''update "user" set phone_number = CONCAT(
        '+98',
        TRIM(LEADING '0' FROM "phoneNumber"))
        where "phoneNumber" is not NULL;
    ''')
    op.drop_column('user', 'phoneNumber')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE "user" RENAME COLUMN country TO country_code')
    op.add_column('user', sa.Column('country_code', sa.VARCHAR(length=8), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('phoneNumber', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'phone_number')
    # ### end Alembic commands ###
