"""empty message

Revision ID: 6298870eb1df
Revises: dcd67bb537e2
Create Date: 2020-02-19 14:05:18.229087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6298870eb1df'
down_revision = 'dcd67bb537e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('''
        UPDATE child
        SET "existence_status" = 1
        WHERE "id" > 0;
    ''')
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
