"""empty message

Revision ID: 70287c7fcbf4
Revises: 4890d13e6493
Create Date: 2020-03-02 23:03:54.378246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70287c7fcbf4'
down_revision = '4890d13e6493'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('payment_order_id_key'), 'payment', ['order_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('payment_order_id_key'), 'payment', type_='unique')
    # ### end Alembic commands ###
