"""empty message

Revision ID: 708fca15d89d
Revises: 1e6d0a1ba9b5
Create Date: 2020-02-06 22:44:40.991778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '708fca15d89d'
down_revision = '1e6d0a1ba9b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('need_family', sa.Column('user_fullname', sa.Text(), nullable=True))
    op.execute('''
        UPDATE need_family nf
        SET user_fullname = concat(u."firstName", ' ', u."lastName")
        FROM "user" u
        WHERE nf.id_user = u.id;
    ''')

    op.execute('''
        ALTER TABLE need_family ALTER COLUMN user_fullname SET NOT NULL;
    ''')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('need_family', 'user_fullname')
    # ### end Alembic commands ###
