"""empty message

Revision ID: 819b92359559
Revises: 79dca1f060ba
Create Date: 2020-08-05 19:17:19.292931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '819b92359559'
down_revision = '79dca1f060ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('''
        UPDATE "user"
        SET "avatarUrl" = concat('/', "avatarUrl")
        where "avatarUrl" = 'public/resources/img/default-avatar.png'
    ''')

    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
