"""empty message

Revision ID: 821fe6e9cbb1
Revises: e1ea0c236309
Create Date: 2020-07-28 03:46:40.244544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '821fe6e9cbb1'
down_revision = 'e1ea0c236309'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('reject_reason', sa.Unicode(length=100), nullable=True))
    op.drop_column('invitations', 'rejected_reason')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('rejected_reason', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('invitations', 'reject_reason')
    # ### end Alembic commands ###
