"""empty message

Revision ID: 99afe9e2e647
Revises: f069672405c4
Create Date: 2020-02-07 16:55:40.590048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99afe9e2e647'
down_revision = 'f069672405c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('need_family', sa.Column('user_role', sa.Integer(), nullable=True))
    op.alter_column('need_family', 'user_avatar',
               existing_type=sa.TEXT(),
               nullable=True)

    op.execute('''
        UPDATE need_family nf
        SET user_role = (CASE WHEN uf."isDeleted" = TRUE THEN -1 ELSE uf."userRole" END)
        FROM user_family uf
        WHERE uf.id_family = nf.id_family AND nf.id_user = uf.id_user;
    ''')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('need_family', 'user_avatar',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('need_family', 'user_role')
    # ### end Alembic commands ###
