"""empty message

Revision ID: 9c60e2651393
Revises: 7648ed29f9be
Create Date: 2019-12-31 16:56:29.966265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c60e2651393'
down_revision = '7648ed29f9be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('activity_id_key'), 'activity', ['id'])
    op.create_foreign_key(op.f('activity_id_social_worker_social_worker_fkey'), 'activity', 'social_worker', ['id_social_worker'], ['id'])
    op.create_unique_constraint(op.f('child_id_key'), 'child', ['id'])
    op.create_foreign_key(op.f('child_id_social_worker_social_worker_fkey'), 'child', 'social_worker', ['id_social_worker'], ['id'])
    op.create_foreign_key(op.f('child_id_ngo_ngo_fkey'), 'child', 'ngo', ['id_ngo'], ['id'])
    op.alter_column('need', 'oncePurchased',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_unique_constraint(op.f('need_id_key'), 'need', ['id'])
    op.drop_constraint('need_child_id_fkey', 'need', type_='foreignkey')
    op.create_foreign_key(op.f('need_child_id_child_fkey'), 'need', 'child', ['child_id'], ['id'])
    op.drop_column('need', 'progress')
    op.create_unique_constraint(op.f('ngo_id_key'), 'ngo', ['id'])
    op.drop_constraint('ngo_coordinator_id_fkey', 'ngo', type_='foreignkey')
    op.create_foreign_key(op.f('ngo_coordinatorId_social_worker_fkey'), 'ngo', 'social_worker', ['coordinatorId'], ['id'])
    op.alter_column('payment', 'donate',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_unique_constraint(op.f('social_worker_id_key'), 'social_worker', ['id'])
    op.create_foreign_key(op.f('social_worker_id_ngo_ngo_fkey'), 'social_worker', 'ngo', ['id_ngo'], ['id'])
    op.create_foreign_key(op.f('social_worker_id_type_social_worker_type_fkey'), 'social_worker', 'social_worker_type', ['id_type'], ['id'])
    op.create_unique_constraint(op.f('social_worker_type_id_key'), 'social_worker_type', ['id'])
    op.alter_column('user', 'isVerified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_unique_constraint(op.f('user_id_key'), 'user', ['id'])
    op.drop_column('user', 'verifyDate')
    op.drop_column('user', 'token')
    op.create_unique_constraint(op.f('verify_id_key'), 'verify', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('verify_id_key'), 'verify', type_='unique')
    op.add_column('user', sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('verifyDate', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('user_id_key'), 'user', type_='unique')
    op.alter_column('user', 'isVerified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(op.f('social_worker_type_id_key'), 'social_worker_type', type_='unique')
    op.drop_constraint(op.f('social_worker_id_type_social_worker_type_fkey'), 'social_worker', type_='foreignkey')
    op.drop_constraint(op.f('social_worker_id_ngo_ngo_fkey'), 'social_worker', type_='foreignkey')
    op.drop_constraint(op.f('social_worker_id_key'), 'social_worker', type_='unique')
    op.alter_column('payment', 'donate',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_constraint(op.f('ngo_coordinatorId_social_worker_fkey'), 'ngo', type_='foreignkey')
    op.create_foreign_key('ngo_coordinator_id_fkey', 'ngo', 'social_worker', ['coordinatorId'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('ngo_id_key'), 'ngo', type_='unique')
    op.add_column('need', sa.Column('progress', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('need_child_id_child_fkey'), 'need', type_='foreignkey')
    op.create_foreign_key('need_child_id_fkey', 'need', 'child', ['child_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('need_id_key'), 'need', type_='unique')
    op.alter_column('need', 'oncePurchased',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint(op.f('child_id_ngo_ngo_fkey'), 'child', type_='foreignkey')
    op.drop_constraint(op.f('child_id_social_worker_social_worker_fkey'), 'child', type_='foreignkey')
    op.drop_constraint(op.f('child_id_key'), 'child', type_='unique')
    op.drop_constraint(op.f('activity_id_social_worker_social_worker_fkey'), 'activity', type_='foreignkey')
    op.drop_constraint(op.f('activity_id_key'), 'activity', type_='unique')
    # ### end Alembic commands ###
