"""empty message

Revision ID: a8268ff1ea6b
Revises: 821fe6e9cbb1
Create Date: 2020-07-28 21:36:58.908400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8268ff1ea6b'
down_revision = '821fe6e9cbb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS PG_TRGM;')
    op.execute('CREATE INDEX username_gin ON "user" USING gin("userName" gin_trgm_ops);')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP INDEX USERNAME_GIN;')
    # ### end Alembic commands ###
