"""empty message

Revision ID: c0ea77b7f629
Revises: 9971e0f64c65
Create Date: 2020-01-22 19:26:23.710959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0ea77b7f629'
down_revision = '9971e0f64c65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('child', sa.Column('firstName_fa', sa.String(), nullable=True))
    op.add_column('child', sa.Column('lastName_fa', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('child', 'lastName_fa')
    op.drop_column('child', 'firstName_fa')
    # ### end Alembic commands ###
