"""empty message

Revision ID: d509c993c888
Revises: 2153402df074
Create Date: 2020-01-22 21:58:34.700453

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy_utils
from babel import Locale


# revision identifiers, used by Alembic.
revision = 'd509c993c888'
down_revision = '2153402df074'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('need', 'description_summary_translations')
    op.add_column(
        'user',
        sa.Column(
            'locale',
            sqlalchemy_utils.types.locale.LocaleType(),
            nullable=False,
            server_default=str(Locale('fa')),
        )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'locale')
    op.add_column('need', sa.Column('description_summary_translations', postgresql.HSTORE(text_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
