"""empty message

Revision ID: e1ea0c236309
Revises: 00feed0d5c61
Create Date: 2020-07-28 03:38:16.302041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1ea0c236309'
down_revision = '00feed0d5c61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('family', sa.Column('say_family_count', sa.Integer(), nullable=True))

    op.execute('UPDATE family f '
               'SET say_family_count = '
               '(SELECT child."sayFamilyCount" FROM child where id = f.id_child);'
               )
    op.drop_column('child', 'sayFamilyCount')

    op.execute('''
        ALTER TABLE family
        ALTER COLUMN say_family_count
        SET NOT NULL;
    ''')

    op.create_index(op.f('family_id_child_idx'), 'family', ['id_child'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('family_id_child_idx'), table_name='family')
    op.drop_column('family', 'say_family_count')
    op.add_column('child', sa.Column('sayFamilyCount', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
