"""empty message

Revision ID: ffe4e31a3ea7
Revises: 04432c7759dd
Create Date: 2020-07-25 21:34:19.157032

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Enum

from say.models import InvitationStatus

# revision identifiers, used by Alembic.
revision = 'ffe4e31a3ea7'
down_revision = '04432c7759dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('invitee_id', sa.Integer(), nullable=True))
    op.add_column('invitations', sa.Column('inviter_id', sa.Integer(), nullable=True))
    op.add_column('invitations', sa.Column('status', sa.VARCHAR(10), nullable=True))
    op.create_foreign_key(op.f('invitations_inviter_id_user_fkey'), 'invitations', 'user', ['inviter_id'], ['id'])
    op.create_foreign_key(op.f('invitations_invitee_id_user_fkey'), 'invitations', 'user', ['invitee_id'], ['id'])
    op.execute('''
        UPDATE invitations SET inviter_id = (select u.id FROM "user" u where u."userName" = 'SAY');
        ALTER TABLE invitations ALTER COLUMN inviter_id SET NOT NULL;
    ''')

    op.execute('''
        UPDATE invitations SET status = 0;
        ALTER TABLE invitations ALTER COLUMN status SET NOT NULL;
    ''')

    op.execute('COMMIT;')
    op.create_index(
         op.f('invitations_inviter_id_idx'),
         'invitations', ['inviter_id'],
         postgresql_concurrently=True,
    )

    op.create_index(
         op.f('invitations_invitee_id_idx'),
         'invitations', ['invitee_id'],
         postgresql_concurrently=True,
    )

    op.create_index(
         op.f('invitations_status_idx'),
         'invitations', ['status'],
         postgresql_concurrently=True,
    )

    op.create_index(
         op.f('invitations_family_id_idx'),
         'invitations', ['family_id'],
         postgresql_concurrently=True,
     )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('invitations_invitee_id_user_fkey'), 'invitations', type_='foreignkey')
    op.drop_constraint(op.f('invitations_inviter_id_user_fkey'), 'invitations', type_='foreignkey')
    op.drop_column('invitations', 'status')
    op.drop_column('invitations', 'inviter_id')
    op.drop_column('invitations', 'invitee_id')
    op.execute('DROP INDEX invitations_family_id_idx')
    # ### end Alembic commands ###
