name: build

on:
  push:
    tags:
    branches:
      - 'master'
      - 'develop'
      - 'release'

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v1
      
      -
        name: Set Docker Image ID
        run: echo ::set-env name=BASE_IMAGE::${{ secrets.REGISTRY }}/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]'):${{ github.ref#refs/heads/}}

      -
        name: Login to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login -u ${{ github.repository_owner }} --password-stdin ${{ secrets.REGISTRY }}
      
      -
        name: Populate cache
        run: docker build --build-arg ENVIRONMENT=$ENVIRONMENT --cache-from ${{ env.BASE_IMAGE }} --target base -t ${{ env.BASE_IMAGE }} .
      
      -
        name: Build
        run: docker build -t tedmiston/tag-example:${GITHUB_REF##*/} .

      #   with:
      #     push: true
      #     tags: ghcr.io/${GITHUB_REPOSITORY}:${GITHUB_REF#refs/heads/}
      # -
      #   name: Image digest
      #   run: echo ${{ steps.docker_build.outputs.digest }}