name: build

on:
  push:
    tags:
    branches:
      - 'master'
      - 'develop'
      - 'release'

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v1
      
      -
        name: Set Docker Image ID
        run: echo "BASE_IMAGE_ID=${{ secrets.REGISTRY }}/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]'):base-${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
        run: echo "RUNTIME_IMAGE_ID=${{ secrets.REGISTRY }}/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]'):${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      -
        name: Login to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login -u ${{ github.repository_owner }} --password-stdin ${{ secrets.REGISTRY }}
      
      -
        name: Pull Base Image Cache
        run: docker pull ${{ env.BASE_IMAGE_ID }} || true
      
      -
        name: Pull Runtime Image Cache
        run: docker pull ${{ env.RUNTIME_IMAGE_ID }} || true

      -
        name: Build Base Image
        run: docker build --build-arg ENVIRONMENT=$ENVIRONMENT --cache-from ${{ env.BASE_IMAGE_ID }} --target base -t ${{ env.BASE_IMAGE_ID }} .

      -
        name: Build Runtime Image
        run: docker build --build-arg ENVIRONMENT=$ENVIRONMENT --cache-from ${{ env.BASE_IMAGE_ID }} --cache-from ${{ env.RUNTIME_IMAGE_ID }} --target prod -t ${{ env.RUNTIME_IMAGE_ID }} .

      -
        name: Push Base Image
        run: docker push ${{ env.BASE_IMAGE_ID }}
      
      -
        name: Push Runtime Image
        run: docker push ${{ env.RUNTIME_IMAGE_ID }}

