name: build

on:
  push:
    tags:
    branches:
      - 'master'
      - 'develop'
      - 'release'

jobs:
  env:
    BASE_IMAGE: ghcr.io/${GITHUB_REPOSITORY}:${GITHUB_REF#refs/heads/}
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v1
      -
        name: Login to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login -u ${{ github.repository_owner }} --password-stdin
      
      -
        name: Populate cache
        run: docker build --build-arg ENVIRONMENT=$ENVIRONMENT --cache-from $BASE_IMAGE --target base -t $BASE_IMAGE .
      
      -
        name: Build
        run: docker build -t tedmiston/tag-example:${GITHUB_REF##*/} .

      #   with:
      #     push: true
      #     tags: ghcr.io/${GITHUB_REPOSITORY}:${GITHUB_REF#refs/heads/}
      # -
      #   name: Image digest
      #   run: echo ${{ steps.docker_build.outputs.digest }}